//import Middleware from './middleware'
import { Bot } from './Bot'
import * as Event from './Event'
import * as Message from './Message'
import * as Base from './Base'
import { Middleware } from './Middleware'
import * as File from './File'
import * as Error from './Error'
import { waitFor } from './Waiter'
export { Bot, File, Event, Message, Base, Middleware, Error, waitFor }
